version: '3'

networks:
  new_admin_panel_sprint_2_admin_panel_network:
    driver: bridge

services:
  postgres_auth:
    container_name: postgres_auth   
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    networks:
      - new_admin_panel_sprint_2_admin_panel_network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data 

  redis:
    image: redis:7
    container_name: redis_auth
    restart: always
    ports:
      - "6379:6379"
    networks:
      - new_admin_panel_sprint_2_admin_panel_network
    volumes:
      - redis_data:/data
  
  auth_service:
    build: .
    container_name: auth_service
    restart: always
    entrypoint: >
      sh -c " python3 utils/wait_for_postgres.py
      && python3 utils/wait_for_redis.py
      && gunicorn --workers 4 --bind 0.0.0.0:5001 src.app:app"
    ports:
      - "5001:5001"
    networks:
      - new_admin_panel_sprint_2_admin_panel_network
    
  nginx:
    image: nginx:1.25
    container_name: nginx_fastapi
    restart: always
    depends_on:
      - auth_service
    ports:
      - "80:80"
    networks:
      - new_admin_panel_sprint_2_admin_panel_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '6831:6831/udp'
      - '16686:16686'
    networks:
      - new_admin_panel_sprint_2_admin_panel_network

volumes:
  postgres_auth_data:
  redis_data:

