"""Adding user agent

Revision ID: 02449c4f845b
Revises: 88cd47d8e102
Create Date: 2023-06-13 21:20:09.420041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02449c4f845b'
down_revision = '88cd47d8e102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_history', sa.Column('user_agent', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_history', 'user_agent')
    # ### end Alembic commands ###
